### ISSUE TITLE
Not Compatible with Ubuntu 16.04 and ROS Kinetic

### ISSUE THREAD

**Issue by rplankenhorn** [ros-naoqi/pepper_meshes#3]
Not Compatible with Ubuntu 16.04 and ROS Kinetic.  The meshes aren't available for Kinetic and I can't access them in rviz.

**Comment by mikaelarguedas** [comment]
The package `pepper_meshes` has not been released yet for Kinetic indeed. I'll release it in the next few days.

In the meantime you can install the meshes from sources using the [meshes installer](https://github.com/ros-naoqi/pepper_meshes_installer) 

Can you give more details about what you mean by "Not compatible with Ubuntu 16.04 and ROS Kinetic"? As far as I know there is nothing ROS Distro specific or Ubuntu distro specific on this package.

**Comment by rplankenhorn** [comment]
@mikaelarguedas Thanks that worked!  I had to copy the meshes to the right folder but I am up and running in rviz.  Let me know when the kinetic package gets released.

**Comment by mikaelarguedas** [comment]
Glad it worked for you, I'll comment on this issue once the package is released.

**Comment by secdec24** [comment]
I had the same issue with the meshes not being available for ROS Kinetic and fixed it as follows:
- git clone repo in your workspace/src
- Create a temporary `build` dir in the newly created `pepper_meshes` dir (I do this to keep my `pepper_meshes` free of clutter)

```
$ cd ~/workspace/src/pepper_meshes
$ mkdir build && cd build
```
- Run cmake

```
$ cmake ..
```
- Go to build folder and run make command

```
$ cd ~/workspace/src/pepper_meshes/build
$ make pepper_meshes_meshes
```
- Move `meshes` dir to the `pepper_meshes` dir

```
$ mv devel/tmp/meshes ../../../
```
- Run catkin_make

```
$ cd ~/workspace
$ ctakin_make
```

Meshes should display correctly in RViz now

While the package `pepper_meshes` for ROS Kinetic is unreleased I'd suggest updating the readme to point users to the meshes installer or to include this procedure. I'd be glad to do that if necessary.

**Comment by mikaelarguedas** [comment]
Thanks @GerardoPrada for detailing the process to get the meshes.

Thanks for offering to change the README accordingly. My only concern is that we are using the same README for all currently alive ros distributions so Indigo/Jade users would assume that they have to go through the hassle of installing them manually while they can just install the corresponding debian package.

Sorry I didn't find the time to port the patches and release `pepper_meshes` on kinetic but will do it ASAP. And in that case I'll advocate not to change the global README so that users of other rosdistros don't get confused.

**Comment by secdec24** [comment]
@mikaelarguedas Makes sense not changing the README if the same one is being used for all distributions. 

Glad you're working on releasing the `pepper_meshes` soon, plus if anyone has any trouble before that they can find the solution here.

**Comment by mikaelarguedas** [comment]
`pepper_meshes` released in https://github.com/ros/rosdistro/pull/12757, it will take a few weeks to get in in the main repo.
