### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by rhaschke** [ros-naoqi/pepper_meshes#5]
Please release for Melodic.

**Comment by mbusy** [comment]
On it. 

@mikaelarguedas: everything seems to be running just fine (tested a local prerelease), but bloom complains about the java rosdep key for stretch:
```
Failed to resolve java on debian:stretch with: Error running generator: Failed to resolve rosdep key 'java', aborting.
java is depended on by these packages: ['pepper_meshes']
```
* since the prerelease runs fine, should I just ignore that ?
* why is java listed as a building dependency, should we remove that ? (I'm guessing that it's linked to the installer, but from my understanding the installer is already built)

**Comment by mikaelarguedas** [comment]
> everything seems to be running just fine (tested a local prerelease), but bloom complains about the java rosdep key for stretch

This means that the prerelease using stretch should fail and not run fine right ?

---

Taking a step back here:
Is this installer needed at all anymore ?

It looks like the meshes are [finally public](https://github.com/ProtolabSBRE/qibullet/tree/1.3.0/qibullet/robot_data/pepper_1.7) and under the [apache 2](https://github.com/ProtolabSBRE/qibullet/blob/1.3.0/LICENSE) license meaning we don't need the installer anymore with license agreement anymore. 
So ideally this package would just get the meshes from qibullet and install them in a ROS package, no more installer and shady patches :tada:

**Comment by mbusy** [comment]
> This means that the prerelease using stretch should fail and not run fine right ?

In my opinion yes, but for some reason the prerelease runs fine... 

---

Regarding the second point, it would definitely be better, I agree. On the other hand, we wanted to replace the meshes - that are starting to get very old :smile: - with a more up-to-date version. But I guess that we won't be able to easily release those updated meshes, and we will potentially need an installer...

So for now, I'd rather keep the current structure for the release (eventually removing the java building dependency), and for the next one either propose a new installer or simply fetching the meshes in another repo (for melodic and kinetic as well)

**Comment by mikaelarguedas** [comment]
> In my opinion yes, but for some reason the prerelease runs fine...

Maybe you ran your prerelease only for ubuntu and did not run one for debian stretch?
```
generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml \
  melodic default **ubuntu bionic** amd64
```

> Regarding the second point, it would definitely be better, I agree. On the other hand, we wanted to replace the meshes - that are starting to get very old smile - with a more up-to-date version. But I guess that we won't be able to easily release those updated meshes, and we will potentially need an installer...

The current installer doesn't work on ARM so any way to fetch the meshes without the installer would be an improvement.
If the meshes can now be put on a repo without explicit license agreement, could we just push the meshes here or pull them from qibullet and avoid the need for an installer?

If we end up needing an installer for future meshes, it would be good to use the same for ROS and qibullet as well as having one that works across platform and architectures.

> eventually removing the java building dependency

My recollection (though it was multiple years ago) is that, as long as we use this installer, the java dependency cannot be removed. When the buildfarm builds the package it needs to have java installed to run the installer

Opened https://github.com/ros/rosdistro/pull/23428 with the rule

---

The kinetic package for pepper_meshes is broken (doesn't display the license agreement on install) while the indigo one does. This should likely be fixed before releasing into melodic

**Comment by mikaelarguedas** [comment]
> The kinetic package for pepper_meshes is broken (doesn't display the license agreement on install) while the indigo one does. This should likely be fixed before releasing into melodic

I should be able to fix this if needed. Question is: is it still needed ?

**Comment by mbusy** [comment]
> Maybe you ran your prerelease only for ubuntu and did not run one for debian stretch?

I might have been a bit fast on that one, I pretested the build on local dockers (bionic and stretch, works fine), but only tried the prerelease for bionic... It indeed fails for stretch.

> The current installer doesn't work on ARM so any way to fetch the meshes without the installer would be an improvement.
If the meshes can now be put on a repo without explicit license agreement, could we just push the meshes here or pull them from qibullet and avoid the need for an installer?

> If we end up needing an installer for future meshes, it would be good to use the same for ROS and qibullet as well as having one that works across platform and architectures.

Someting that I failed to mention, the qibullet meshes are not identical to the ROS ones, the meshes had to be adapted for bullet... Just pulling the meshes won't do it, they will have to be "reverted" to their initial state (since the changes were made manually, I don't have a script to do so). 

Regarding the second comment, I agree, the same installer would be good, I would add extra installation rules in qibullet to adapt the meshes. 

So for now, even though it's not ideal, I think that it's better to keep things that way, with the fix for the kinetic package. In the meantime, I'll see internally how I can release the updated meshes, to have a unified way of installing that

**Comment by mikaelarguedas** [comment]
> So for now, even though it's not ideal, I think that it's better to keep things that way, with the fix for the kinetic package. In the meantime, I'll see internally how I can release the updated meshes, to have a unified way of installing that

Awesome

**Comment by mikaelarguedas** [comment]
@Pandhariix if it's fine with you, I'll make the melodic release and post a comment with all the relevant PRs here to ease future release (e.g. upcoming Noetic)

**Comment by mbusy** [comment]
@mikaelarguedas sure, thanks !

**Comment by mikaelarguedas** [comment]
PRs:
- Adding missing java rosdep rule for debian stretch: https://github.com/ros/rosdistro/pull/23428
- Blacklisting the packages mesh packages on arm: https://github.com/ros-infrastructure/ros_buildfarm_config/pull/158
- Port patches to display license at package install time: https://github.com/ros-naoqi/pepper_meshes-release/pull/1
- Skipped fedora and requested removal of EOL fedora distro https://github.com/ros/rosdistro/pull/23445

Process to release:
- catkin_generate_changelogs + catkin_prepare_release
- Run bloom once (skipping fedora) without opening the PR (`--no-pull-request`)
- Clone the repo, checkout `debian/melodic/pepper_meshes`, cherry-pick 81a1e11b9f5d572a666814afff6a0f429a0fcc6c, push it
- Run bloom a second time, this time opening the PR: https://github.com/ros/rosdistro/pull/23446

**Comment by mikaelarguedas** [comment]
`pepper_meshes` has been released for ROS Melodic and should be available in the next melodic sync.

If you want to give a try to the package right now you can install it from the [testing repository](http://wiki.ros.org/TestingRepository)
